/**
 * Security response headers, applied per-request from `src/middleware.ts` so
 * the HTTPS-gated headers below honor the `AK_ENFORCE_HTTPS` env var at
 * container runtime, not just at build time (#679).
 *
 * Header delivery is split in two within the middleware:
 *
 *   - Static, request-independent headers (X-Frame-Options, nosniff, HSTS, …)
 *     come from `buildSecurityHeaders()`.
 *   - The `Content-Security-Policy` is built per request by
 *     `buildContentSecurityPolicy()`, because it embeds a per-request nonce
 *     for `script-src`. Next.js parses the nonce out of the
 *     `Content-Security-Policy` **request** header during SSR and stamps it
 *     onto every framework script it renders (bootstrap, page bundles,
 *     `next/script`), which is what lets `script-src` drop `'unsafe-inline'`.
 *
 * Two of the headers only make sense when the deployment actually terminates
 * TLS, and are actively harmful on a plain-HTTP deployment:
 *
 *   - `Strict-Transport-Security` (HSTS)
 *   - the `upgrade-insecure-requests` CSP directive
 *
 * On the common first-run default deployment (`http://<IP>:30080`, no TLS),
 * `upgrade-insecure-requests` makes the browser rewrite every same-origin
 * request from http:// to https://. Port 30080 only serves plain HTTP, so the
 * upgraded `https://<IP>:30080/*.js` requests fail to connect and the whole UI
 * becomes inaccessible. See artifact-keeper/artifact-keeper#2222.
 *
 * These two are therefore gated behind an explicit opt-in
 * (`AK_ENFORCE_HTTPS`), default OFF, so a plain-HTTP default deploy works out
 * of the box while real TLS deployments keep the hardening.
 */

export interface SecurityHeader {
  key: string;
  value: string;
}

/**
 * Request header the middleware uses to hand the per-request nonce to the
 * root layout (read via `headers()` and passed to `next-themes`, the one
 * inline script Next.js does not nonce automatically).
 */
export const NONCE_HEADER = "x-nonce";

/**
 * Generate a per-request CSP nonce.
 *
 * Uses only web-standard APIs (`crypto.randomUUID` + `btoa`), so it is safe
 * in both the Node.js and edge middleware runtimes — no `node:crypto`.
 */
export function generateNonce(): string {
  return btoa(crypto.randomUUID());
}

export interface CspOptions {
  /**
   * Append `'unsafe-eval'` to `script-src`. Required in development, where
   * React uses `eval` to reconstruct server-side error stacks in the browser.
   * Never needed in production.
   */
  allowUnsafeEval?: boolean;
}

/**
 * Build the `Content-Security-Policy` value for a single request.
 *
 * `nonce` is the per-request nonce generated by the middleware; it is placed
 * in `script-src` so only scripts stamped with it (by Next.js during SSR, or
 * explicitly via `next-themes`' `nonce` prop) may execute. `'strict-dynamic'`
 * lets those trusted scripts load further scripts (Next.js lazy chunks)
 * without allow-listing every URL; CSP3 browsers ignore `'self'` when
 * `'strict-dynamic'` is present, so the allowlist is only a fallback for
 * older browsers.
 *
 * Directive notes:
 *
 *   - `style-src` keeps `'unsafe-inline'`: Shiki syntax highlighting renders
 *     colors as inline `style` attributes, and nonces do not cover style
 *     attributes. Inline styles are a much smaller XSS surface than scripts.
 *   - `object-src 'self'` (not `'none'`): the package file viewer renders
 *     PDFs via `<object type="application/pdf">` against a same-origin
 *     download URL (`/api/v1/repositories/.../download/...`).
 *   - `connect-src 'self' https:`: the remote-instances feature health-checks
 *     user-configured instances by fetching `https://<remote>/health`
 *     cross-origin from the browser (`instance-provider.tsx`). Plain-`http`
 *     remotes are intentionally not permitted: any TLS-fronted deployment
 *     would block them as mixed content anyway.
 *
 * The `upgrade-insecure-requests` directive is only appended when the
 * deployment serves the UI over HTTPS. Built programmatically from a
 * directive list so conditional directives can never leave a malformed
 * `"; "` suffix.
 */
export function buildContentSecurityPolicy(
  httpsEnabled: boolean,
  nonce: string,
  { allowUnsafeEval = false }: CspOptions = {},
): string {
  const directives = [
    "default-src 'self'",
    `script-src 'self' 'nonce-${nonce}' 'strict-dynamic'${allowUnsafeEval ? " 'unsafe-eval'" : ""}`,
    "style-src 'self' 'unsafe-inline'",
    "img-src 'self' data: blob:",
    "font-src 'self' data:",
    "connect-src 'self' https:",
    "object-src 'self'",
    "worker-src 'self'",
    "frame-ancestors 'none'",
    "base-uri 'self'",
    "form-action 'self'",
  ];
  if (httpsEnabled) {
    directives.push("upgrade-insecure-requests");
  }
  return directives.join("; ");
}

/**
 * Build the request-independent security headers applied to every response
 * (page pass-through, proxied API responses, and the SSE pass-through) from
 * `src/middleware.ts`. The `Content-Security-Policy` header is deliberately
 * NOT included: it carries a per-request nonce and is built separately via
 * `buildContentSecurityPolicy()`.
 *
 * When `httpsEnabled` is false (the default), HSTS is omitted; every other
 * header is unconditional.
 */
export function buildSecurityHeaders(httpsEnabled: boolean): SecurityHeader[] {
  const headers: SecurityHeader[] = [
    { key: "X-Frame-Options", value: "DENY" },
    { key: "X-Content-Type-Options", value: "nosniff" },
    { key: "Referrer-Policy", value: "strict-origin-when-cross-origin" },
    {
      key: "Permissions-Policy",
      value: "camera=(), microphone=(), geolocation=()",
    },
    // "off" is the conventional hardening value: the app renders
    // attacker-controlled content and should not leak lookup hints for
    // hostnames embedded in it via DNS prefetching.
    { key: "X-DNS-Prefetch-Control", value: "off" },
  ];

  if (httpsEnabled) {
    headers.push({
      key: "Strict-Transport-Security",
      value: "max-age=31536000; includeSubDomains",
    });
  }

  return headers;
}

/**
 * Whether the deployment serves the web UI over HTTPS (TLS terminated),
 * controlled by the `AK_ENFORCE_HTTPS` env var.
 *
 * Set `AK_ENFORCE_HTTPS=true` (or `1`) when the UI is served behind TLS to
 * enable HSTS + `upgrade-insecure-requests`. Leave unset/false for plain-HTTP
 * deployments. Any other value is treated as false.
 *
 * NOTE: this is consumed from `src/middleware.ts`, which runs per request, so
 * the flag is read at container RUNTIME (e.g. `docker run -e
 * AK_ENFORCE_HTTPS=true`), not baked into the image at build time. See #679.
 */
export function isHttpsEnabled(
  env: Record<string, string | undefined> = process.env,
): boolean {
  const flag = env.AK_ENFORCE_HTTPS;
  return flag === "true" || flag === "1";
}
