/**
 * i18n message group manifest (generated by scripts/split-i18n.cjs).
 *
 * Message catalogs are split by functional domain (mirroring the app route
 * structure) so each route only loads the groups it needs. See
 * src/i18n/load-messages.ts for the per-route loader.
 */
export const messageGroups = {
  "core": [
    "common",
    "ui",
    "errorPages",
    "authError",
    "severity",
    "localeSwitcher"
  ],
  "auth": [
    "login",
    "ssoCallback",
    "changePassword"
  ],
  "app": [
    "sidebar",
    "header",
    "demoBanner",
    "passwordExpiry",
    "instanceSwitcher",
    "skipNav",
    "dashboard"
  ],
  "guides": [
    "setupGuide"
  ],
  "protected": [
    "accessTokens",
    "peers",
    "plugins",
    "profile",
    "replication",
    "webhooks"
  ],
  "admin": [
    "adminAgeGate",
    "adminAnalytics",
    "adminApprovals",
    "adminAudit",
    "adminBackups",
    "adminBlastRadius",
    "adminCuration",
    "adminCurationRules",
    "adminDownloads",
    "adminDtProjectDetail",
    "adminDtProjects",
    "adminError",
    "adminFormatHandlers",
    "adminGroups",
    "adminLicensePolicies",
    "adminLifecycle",
    "adminMigration",
    "adminMonitoring",
    "adminPermissions",
    "adminPromotionRules",
    "adminQualityChecks",
    "adminQualityGates",
    "adminRateLimits",
    "adminScanDetail",
    "adminScans",
    "adminSecurity",
    "adminSecurityPolicies",
    "adminServiceAccounts",
    "adminSettings",
    "adminSettingsSso",
    "adminSigning",
    "adminSyncPolicies",
    "adminSystemHealth",
    "adminTelemetry",
    "adminUsers"
  ],
  "repositories": [
    "repositories",
    "repoDetail",
    "repoDialogs",
    "repoSettings",
    "repoLabels",
    "folderStorage",
    "artifactBrowser",
    "artifactScans",
    "artifactVersions",
    "artifactTree",
    "mavenComponents",
    "dockerTags",
    "packageDependencies",
    "packageMetadata",
    "formatConfig",
    "pypiTracks",
    "releaseTarget",
    "virtualMembers",
    "routingRules",
    "notifications",
    "securityTab",
    "sbom",
    "packagesTab",
    "health",
    "storage"
  ],
  "packages": [
    "packages",
    "packageDetail"
  ],
  "builds": [
    "builds"
  ],
  "search": [
    "search"
  ],
  "setup": [
    "setup"
  ],
  "staging": [
    "staging",
    "rejection",
    "promotion",
    "promotionHistory"
  ]
} as const;

export type MessageGroup = keyof typeof messageGroups;

/** All group names, for test setups that need the full catalog. */
export const ALL_GROUPS = Object.keys(messageGroups) as MessageGroup[];
